### ISSUE TITLE
Many fields are not translatabel

### ISSUE THREAD

**Issue by akram1** [dreispt/todo_app#1]
Nice app. Many fields are needed to set to translatable.

**Comment by dreispt** [comment]
Thanks for the interest.
This app is in fact meant to showcase Odoo development.
It is the source code for the upcoming book [Odoo Essentials](https://www.packtpub.com/big-data-and-business-intelligence/odoo-essentials).

For actual usage, you will be better served using the official [Notes](https://www.odoo.com/apps/modules/online/note/) app.
_PS: the NoteClientApp provided here is a desktop client that works with the Notes official app._
