### ISSUE TITLE
To-do Task Wizard not showing in "More" menu

### ISSUE THREAD

**Issue by akhasis** [dreispt/todo_app#11]
Hello,
i'm following your tutorial on making a to-do app in Odoo 8. I have spent days trying to make the option To-do Task Wizard show in the "More" button menu, with the code in this repo, with no luck.

I finally succeeded, by deleting the "Multi" attribute, which is set to True in the act_windows description in your code. Searching online, the purpose of the attribute seems to be to hide the option from said menu, which is consistent with my issue. 

Please, consider editing it in the code, or correct me if I'm wrong (which is quite possible, since this is my first contact with Python).

Thank you for your tutorial, it is really clear and educational.

**Comment by dreispt** [comment]
The "multi" attribute means that the Action is to be applied to multiple items. That means that you need to first select some items from a list for the Action to be available in "More".
Otherwise is is available only in the Form view.
I think I improved this in the 11.0 code.
