### ISSUE TITLE
Attribute default_group_by in the kanban tag inside the todo_kanban module view (todo_view.xml)

### ISSUE THREAD

**Issue by eduardobape** [dreispt/todo_app#3]
I think that an error exists in the attribute default_group_by in the kanbag tag inside the todo_kanban module view (todo_view.xml file).

The original value is: `<kanban default_group_by="stage">`.
I think that the correct value would be this: `<kanban default_group_by="stage_id">`, because the field name of the TodoTask class in the todo_ui module is `stage_id`, not `stage`.

**Comment by dreispt** [comment]
Yes, you are right: the correct field name is `stage_id`

**Comment by dreispt** [comment]
Fixed by https://github.com/dreispt/todo_app/commit/823006fd7c9d5321c38b2df55e4dd8808fc52493
