### ISSUE TITLE
Odoo Development Essentials on Github Repo?

### ISSUE THREAD

**Issue by lukebranch** [dreispt/todo_app#5]
@dreispt ,

I've just come across a PDF in a public github repo that seems to contain a PDF copy of your book:

[link removed for the sake of not drawing more attention to it]

I thought i'd bring it to your attention just in case it was unauthorised.

**Comment by dreispt** [comment]
It certainly is not, thank you for bringing it to my attention. I'll alert the publisher.
Even if intentions are good, It certainly isn't ethic to publish it like that.
It is disrespectful on the work of the people involved, not only me, but also all Pack workers that made it possible.

**Comment by dreispt** [comment]
I just brought the authors to attention. I hope they are honest about it.
Thanks again!

**Comment by lukebranch** [comment]
@dreispt ,

No problem. I came across the link randomly in a google search and thought I should let you know.

I've removed the link from my comment so that no one else's attention is brought to this unauthorised copy while yourself and packt are sorting this out.
